image: tmy2017/gitpod-pstorm-with-php71-mysql8:ver-1640846949
tasks:
  # change version php 
  - before: |
      sudo add-apt-repository ppa:ondrej/php -y && \
      sudo install-packages php7.2 php7.2-xdebug php7.2-mysql php7.2-intl php7.2-mbstring php7.2-curl php7.2-simplexml && \
      sudo update-alternatives --set php /usr/bin/php7.2
      php -r "copy('https://getcomposer.org/installer', 'composer-setup.php');"
      php -r "if (hash_file('sha384', 'composer-setup.php') === '906a84df04cea2aa72f40b5f787e49f22d4c2f19492ac310e8cba5b96ac8b64115ac402c8cd292b8a03482574915d1a8') { echo 'Installer verified'; } else { echo 'Installer corrupt'; unlink('composer-setup.php'); } echo PHP_EOL;"
      sudo php composer-setup.php --install-dir /usr/bin --filename composer
      php -r "unlink('composer-setup.php');"    
    init: |
      echo 'TODO: build project'
    command: |
      echo 'TODO: start app'